config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :bookings
  get '/query' => "properties#query"
  root to: redirect('/query')

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :author
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @start_date = Date.new(params[:booking]["start(1i)"].to_i, params[:booking]["start(2i)"].to_i, params[:booking]["start(3i)"].to_i)
    @end_date = Date.new(params[:booking]["end(1i)"].to_i, params[:booking]["end(2i)"].to_i, params[:booking]["end(3i)"].to_i)
    @properties = Property.joins(:bookings).where(:location => params[:property][:location]).where.not(bookings: {:start => @start_date..@end_date, :end => @start_date..@end_date})
  end

  def query
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EXAM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/index.html.haml
%h1 Available properties

%table#properties
  %thead
    %tr
      %th Name
      %th Location
      %th Cost
      %th Area
      %th Floor
      %th Services

  %tbody
    - @properties.each do |p|
      %tr
        %td= p.name
        %td= p.location
        %td= p.cost
        %td= p.area
        %td= p.floor
        %td= p.services

app/views/properties/query.html.haml
%h2 Find Property

= form_tag properties_path, :method => :get do
  = label :property, :location, 'Location'
  = text_field :property, :location
  %br

  = label :booking, :start, 'Start'
  = date_select :booking, :start
  %br

  = label :booking, :end, 'End'
  = date_select :booking, :end
  %br
  %br

  = submit_tag 'Submit'